### ISSUE TITLE
Allow deleting CODEMETA and CITATION

### ISSUE THREAD

**Issue by serjflint** [dmyersturnbull/tyrannosaurus#52]
I disabled codemeta and citation for my proprietary project. But I cannot delete corresponding files.

- **Project version:** 0.9.6
- **OS/platform:** Manjaro 20

```
❯ tyrannosaurus sync
Running: tyrannosaurus sync
Syncing metadata...
Currently, only targets 'init' and 'recipe' are implemented.
Traceback (most recent call last):
  File "/virtualenvs/project/bin/tyrannosaurus", line 8, in <module>
    sys.exit(cli())
  File "/virtualenvs/project/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/cli.py", line 230, in sync
    targets = Sync(context).sync()
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/sync.py", line 35, in sync
    self.fix_citation()
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/sync.py", line 92, in fix_citation
    return self._replace_substrs(
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/sync.py", line 205, in _replace_substrs
    self.context.back_up(path)
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/context.py", line 127, in back_up
    self.check_path(path)
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/context.py", line 169, in check_path
    raise FileNotFoundError(f"Path {path} does not exist")
FileNotFoundError: Path /project/CITATION.cff does not exist
Traceback (most recent call last):
  File "/virtualenvs/project/bin/tyrannosaurus", line 8, in <module>
    sys.exit(cli())
  File "/virtualenvs/project/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/virtualenvs/project/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/virtualenvs/project/lib/python3.9/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/cli.py", line 387, in build
    CliCommands.build_internal(bare=bare, dry=state.dry_run)
  File "/virtualenvs/project/lib/python3.9/site-packages/tyrannosaurus/cli.py", line 400, in build_internal
    check_call(cmd.split(" "))  # nosec
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tyrannosaurus', 'sync']' returned non-zero exit status 1.
```

**Comment by dmyersturnbull** [comment]
It should work if you remove those two items from `[tyrannosaurus.targets]`.
I just committed a fix so that it ignores those if the files don't exist, even if they're listed in `targets`.
